# Deployment para la app express
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-express
  template:
    metadata:
      labels:
        app: app-express
    spec:
      containers:
      - name: app-express
        image: xatomen/app-express:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---
# Exponer servicio con un LoadBalancer
kind: Service
apiVersion: v1
metadata:
  name: app-express
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: app-express